In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn import preprocessing
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split # Import train_test_split function
import warnings
warnings.filterwarnings("ignore")

In [54]:
dataset_train=pd.read_csv(r"C:\Users\Dell\Desktop\KDDTest-21.txt")
dataset_test=pd.read_csv(r"C:\Users\Dell\Desktop\KDDTrain+.txt")

In [55]:
dataset_train.head(10)
dataset_test.head(10)

,0,tcp,ftp_data,SF,491,0.1,0.2,0.3,0.4,0.5,...,0.17,0.03,0.17.1,0.00.6,0.00.7,0.00.8,0.05,0.00.9,normal,20
0,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal,15
1,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune,19
2,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal,21
3,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal,21
4,0,tcp,private,REJ,0,0,0,0,0,0,...,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune,21
5,0,tcp,private,S0,0,0,0,0,0,0,...,0.04,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune,21
6,0,tcp,private,S0,0,0,0,0,0,0,...,0.06,0.07,0.00,0.00,1.00,1.00,0.0,0.00,neptune,21
7,0,tcp,remote_job,S0,0,0,0,0,0,0,...,0.09,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune,21
8,0,tcp,private,S0,0,0,0,0,0,0,...,0.05,0.06,0.00,0.00,1.00,1.00,0.0,0.00,neptune,21
9,0,tcp,private,REJ,0,0,0,0,0,0,...,0.05,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune,21

In [56]:
#remove last column

dataset_train = dataset_train.drop(dataset_train.columns[-1], axis=1)

dataset_test = dataset_test.drop(dataset_test.columns[-1], axis=1)

In [57]:
dataset_train.head(10)

,13,tcp,telnet,SF,118,2425,0,0.1,0.2,0.3,...,10,0.38,0.12,0.04,0.00.6,0.00.7,0.00.8,0.12.1,0.30,guess_passwd
0,0,udp,private,SF,44,0,0,0,0,0,...,254,1.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,snmpguess
1,0,tcp,telnet,S3,0,44,0,0,0,0,...,79,0.31,0.61,0.00,0.00,0.21,0.68,0.60,0.00,processtable
2,0,udp,private,SF,53,55,0,0,0,0,...,255,1.00,0.00,0.87,0.00,0.00,0.00,0.00,0.00,normal
3,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.06,1.00,1.00,0.00,1.00,1.00,0.00,0.00,nmap
4,0,tcp,http,SF,54540,8314,0,0,0,2,...,229,0.90,0.01,0.00,0.00,0.00,0.00,0.01,0.00,back
5,0,tcp,imap4,REJ,0,0,0,0,0,0,...,9,0.04,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
6,7570,tcp,telnet,SF,0,44,0,0,0,0,...,165,0.65,0.33,0.00,0.00,0.49,0.76,0.33,0.01,processtable
7,0,udp,private,SF,56,52,0,0,0,0,...,255,1.00,0.00,0.93,0.00,0.00,0.00,0.00,0.00,normal
8,0,tcp,ftp_data,SF,192,0,0,0,0,0,...,51,0.09,0.04,0.09,0.04,0.00,0.00,0.01,0.00,normal
9,0,tcp,other,REJ,0,0,0,0,0,0,...,1,0.00,0.94,0.00,0.00,0.13,0.00,0.87,1.00,satan

In [58]:
dataset_test.head(10)

,0,tcp,ftp_data,SF,491,0.1,0.2,0.3,0.4,0.5,...,25,0.17,0.03,0.17.1,0.00.6,0.00.7,0.00.8,0.05,0.00.9,normal
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune
5,0,tcp,private,S0,0,0,0,0,0,0,...,9,0.04,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
6,0,tcp,private,S0,0,0,0,0,0,0,...,15,0.06,0.07,0.00,0.00,1.00,1.00,0.0,0.00,neptune
7,0,tcp,remote_job,S0,0,0,0,0,0,0,...,23,0.09,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
8,0,tcp,private,S0,0,0,0,0,0,0,...,13,0.05,0.06,0.00,0.00,1.00,1.00,0.0,0.00,neptune
9,0,tcp,private,REJ,0,0,0,0,0,0,...,12,0.05,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune

In [60]:
dataset_test.columns = ["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

In [61]:
dataset_test.head(10)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune
5,0,tcp,private,S0,0,0,0,0,0,0,...,9,0.04,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
6,0,tcp,private,S0,0,0,0,0,0,0,...,15,0.06,0.07,0.00,0.00,1.00,1.00,0.0,0.00,neptune
7,0,tcp,remote_job,S0,0,0,0,0,0,0,...,23,0.09,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
8,0,tcp,private,S0,0,0,0,0,0,0,...,13,0.05,0.06,0.00,0.00,1.00,1.00,0.0,0.00,neptune
9,0,tcp,private,REJ,0,0,0,0,0,0,...,12,0.05,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune

In [62]:
dataset_train.columns = ["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

In [63]:
dataset_train.head(10)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,udp,private,SF,44,0,0,0,0,0,...,254,1.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,snmpguess
1,0,tcp,telnet,S3,0,44,0,0,0,0,...,79,0.31,0.61,0.00,0.00,0.21,0.68,0.60,0.00,processtable
2,0,udp,private,SF,53,55,0,0,0,0,...,255,1.00,0.00,0.87,0.00,0.00,0.00,0.00,0.00,normal
3,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.06,1.00,1.00,0.00,1.00,1.00,0.00,0.00,nmap
4,0,tcp,http,SF,54540,8314,0,0,0,2,...,229,0.90,0.01,0.00,0.00,0.00,0.00,0.01,0.00,back
5,0,tcp,imap4,REJ,0,0,0,0,0,0,...,9,0.04,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
6,7570,tcp,telnet,SF,0,44,0,0,0,0,...,165,0.65,0.33,0.00,0.00,0.49,0.76,0.33,0.01,processtable
7,0,udp,private,SF,56,52,0,0,0,0,...,255,1.00,0.00,0.93,0.00,0.00,0.00,0.00,0.00,normal
8,0,tcp,ftp_data,SF,192,0,0,0,0,0,...,51,0.09,0.04,0.09,0.04,0.00,0.00,0.01,0.00,normal
9,0,tcp,other,REJ,0,0,0,0,0,0,...,1,0.00,0.94,0.00,0.00,0.13,0.00,0.87,1.00,satan

In [82]:
print('Training set:')
for col_name in dataset_train.columns:
    if dataset_test[col_name].dtypes == 'object' :
        unique_cat = len(dataset_test[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

Training set:
Feature 'protocol_type' has 3 categories
Feature 'service' has 70 categories
Feature 'flag' has 11 categories
Feature 'label' has 23 categories

KeyError: 'protocol_type_encoded'

In [75]:

dataset_train['protocol_type'].replace({ 'udp' : 0, 'tcp' : 1 ,'icmp': 2 },inplace = True)

In [76]:
dataset_train.head(10)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,protocol_type_encoded
0,0,0,private,SF,44,0,0,0,0,0,...,1.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,snmpguess,0.0
1,0,1,telnet,S3,0,44,0,0,0,0,...,0.31,0.61,0.00,0.00,0.21,0.68,0.60,0.00,processtable,1.0
2,0,0,private,SF,53,55,0,0,0,0,...,1.00,0.00,0.87,0.00,0.00,0.00,0.00,0.00,normal,0.0
3,0,1,private,SH,0,0,0,0,0,0,...,0.06,1.00,1.00,0.00,1.00,1.00,0.00,0.00,nmap,1.0
4,0,1,http,SF,54540,8314,0,0,0,2,...,0.90,0.01,0.00,0.00,0.00,0.00,0.01,0.00,back,1.0
5,0,1,imap4,REJ,0,0,0,0,0,0,...,0.04,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune,1.0
6,7570,1,telnet,SF,0,44,0,0,0,0,...,0.65,0.33,0.00,0.00,0.49,0.76,0.33,0.01,processtable,1.0
7,0,0,private,SF,56,52,0,0,0,0,...,1.00,0.00,0.93,0.00,0.00,0.00,0.00,0.00,normal,0.0
8,0,1,ftp_data,SF,192,0,0,0,0,0,...,0.09,0.04,0.09,0.04,0.00,0.00,0.01,0.00,normal,1.0
9,0,1,other,REJ,0,0,0,0,0,0,...,0.00,0.94,0.00,0.00,0.13,0.00,0.87,1.00,satan,1.0

In [77]:
dataset_train['flag'].replace({ 'OTH' : 0, 'REJ' : 1 ,'RSTO': 2 ,'RSTOS0':3 ,'RSTR': 4,'S0':5, 'S1':6,'S2':7, 'S3':8, 'SF':9,'SH':10 },inplace = True)

In [78]:
dataset_train.head(10)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,protocol_type_encoded
0,0,0,private,9,44,0,0,0,0,0,...,1.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,snmpguess,0.0
1,0,1,telnet,8,0,44,0,0,0,0,...,0.31,0.61,0.00,0.00,0.21,0.68,0.60,0.00,processtable,1.0
2,0,0,private,9,53,55,0,0,0,0,...,1.00,0.00,0.87,0.00,0.00,0.00,0.00,0.00,normal,0.0
3,0,1,private,10,0,0,0,0,0,0,...,0.06,1.00,1.00,0.00,1.00,1.00,0.00,0.00,nmap,1.0
4,0,1,http,9,54540,8314,0,0,0,2,...,0.90,0.01,0.00,0.00,0.00,0.00,0.01,0.00,back,1.0
5,0,1,imap4,1,0,0,0,0,0,0,...,0.04,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune,1.0
6,7570,1,telnet,9,0,44,0,0,0,0,...,0.65,0.33,0.00,0.00,0.49,0.76,0.33,0.01,processtable,1.0
7,0,0,private,9,56,52,0,0,0,0,...,1.00,0.00,0.93,0.00,0.00,0.00,0.00,0.00,normal,0.0
8,0,1,ftp_data,9,192,0,0,0,0,0,...,0.09,0.04,0.09,0.04,0.00,0.00,0.01,0.00,normal,1.0
9,0,1,other,1,0,0,0,0,0,0,...,0.00,0.94,0.00,0.00,0.13,0.00,0.87,1.00,satan,1.0

In [83]:
dataset_train['service'].replace({ 'aol':0,'auth':1,'bgp':2,'courier':3,'csnet_ns':4,'ctf':5,'daytime':6,'discard':7,'domain':8,
'domain_u':9,'echo':10,'eco_i':11,'ecr_i':12, 'efs':13,'exec':14,'finger':15,'ftp':16,'ftp_data':17,'gopher':18,'harvest':19,
'hostnames':20,'http':21,'http_2784':22,'http_443':23,'http_8001':24,'imap4':25,'IRC':26, 'iso_tsap':27,'klogin':28,'kshell':29,
'ldap':30,'link':31,'login':32,'mtp':33,'name':34,'netbios_dgm':35,'netbios_ns':36,'netbios_ssn':37,'netstat':38,'nnsp':39,
'nntp':40,'ntp_u':41,'other':42,'pm_dump':43,'pop_2':44,'pop_3':45,'printer':46,'private':47,'red_i':48,'remote_job':49,
'rje':50,'shell':51,'smtp':52,'sql_net':53,'ssh':54,'sunrpc':55,'supdup':56,'systat':57,'telnet':58,'tftp_u':59,'tim_i':60,
'time':61,'urh_i':62,'urp_i':63,'uucp':64,'uucp_path':65,'vmnet':66,'whois':67,'X11':68,'Z39_50':69})

0        47
1        58
2        47
3        47
4        21
         ..
11844     9
11845    21
11846    58
11847    55
11848    47
Name: service, Length: 11849, dtype: int64

In [84]:
dataset_train['label'].replace({ 'normal' : 0, 'neptune' : 1 ,'back': 1, 'land': 1, 'pod': 1, 'smurf': 1, 'teardrop': 1,'mailbomb': 1,
                       'apache2': 1, 'processtable': 1, 'udpstorm': 1, 'worm': 1,'ipsweep' : 0,'nmap' : 0,'portsweep' : 0,
                       'satan' : 0,'mscan' : 0,'saint' : 0,'ftp_write': 0,'guess_passwd': 0,'imap': 0,'multihop': 0,'phf': 0,
                       'spy': 0,'warezclient': 0,'warezmaster': 0,'sendmail': 0,'named': 0,'snmpgetattack': 0,'snmpguess': 0,
                       'xlock': 0,'xsnoop': 0,'httptunnel': 0,'buffer_overflow': 0,'loadmodule': 0,'perl': 0,'rootkit': 0,
                       'ps': 0,'sqlattack': 0,'xterm': 0},inplace = True)